trigger: 
 branches:
  include:
    - main

pool: bipinpool

# variables:
# - group: Azure_Subscription
# - name: ARM_SUBSCRIPTION_ID
#   value: $(ARM_SUBSCRIPTION_ID)

stages:
- stage: TerrafomInitPlan
  jobs:
  - job: InitPlan
    steps:
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'infra-pipeline-azure'
        backendAzureRmResourceGroupName: 'dev-rg1'
        backendAzureRmStorageAccountName: 'devstgacbk01'
        backendAzureRmContainerName: 'devcont'
        backendAzureRmKey: 'bk.terraform.tfstate'
    - task: TerraformTaskV4@4
      # env:
      #   TF_VAR_subscription_id: $(ARM_SUBSCRIPTION_ID)
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'infra-pipeline-azure'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'infra-pipeline-azure'