name: InfraDeploymentPipeline
pool: "Bipin Agent"

trigger:
- main
- dev

jobs:
  - job: "Terraform-Job"
    steps:
      - 
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
    
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'pipeline-connection-infra'
    backendAzureRmResourceGroupName: 'bipin-rg'
    backendAzureRmStorageAccountName: 'bkumar765'
    backendAzureRmContainerName: 'tfstatecontainer'
    backendAzureRmKey: 'prod.tfstate'