name: InfraDeploymentPipeline
pool: Bipin Agent

trigger:
- main
- develop

stages:
- stage: Terraforminitplan
  displayName: Terraform Init
  pool: Bipin Agent
  jobs:
  - job: terraformjob
    steps:
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
    
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'pipeline-connection-infra'
        backendAzureRmResourceGroupName: 'bipin-rg'
        backendAzureRmStorageAccountName: 'bkumar765'
        backendAzureRmContainerName: 'tfstatecontainer'
        backendAzureRmKey: 'terra.tfstate'

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'pipeline-connection-infra'
        
