trigger: 
 branches:
  include:
    - main

pool: bipinpool

variables:
- group: Azure_Subscription
- name: ARM_SUBSCRIPTION_ID
  value: $(ARM_SUBSCRIPTION_ID)

stages:
- stage: TerrafomInitPlan
  jobs:
  - job: InitPlan
    steps:
    - task: TerraformTaskV4@4
      env:
        TF_VAR_subscription_id: $(ARM_SUBSCRIPTION_ID)
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Free Trial(2765d1c6-42ae-4328-9ed0-6fb92093c18e)'
        backendAzureRmResourceGroupName: 'dev-rg1'
        backendAzureRmStorageAccountName: 'devstgacbk01'
        backendAzureRmContainerName: 'devcont'
        backendAzureRmKey: 'bk.terraform.tfstate'